// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/header/header.vue')['default']
    Loading: typeof import('./src/components/base/loading/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/base/scroll/scroll.vue')['default']
    Slider: typeof import('./src/components/base/slider/slider.vue')['default']
    Tab: typeof import('./src/components/tab/tab.vue')['default']
  }
}

export { }
