// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/base/dialog/dialog.vue')['default']
    Header: typeof import('./src/components/header/header.vue')['default']
    IndexList: typeof import('./src/components/index-list/index-list.vue')['default']
    Loading: typeof import('./src/components/base/loading/loading.vue')['default']
    MiniPlayer: typeof import('./src/components/player/mini-player.vue')['default']
    MusicList: typeof import('./src/components/music-list/music-list.vue')['default']
    NoResult: typeof import('./src/components/base/no-result/no-result.vue')['default']
    Player: typeof import('./src/components/player/player.vue')['default']
    Playlist: typeof import('./src/components/player/playlist.vue')['default']
    ProgressBar: typeof import('./src/components/player/progress-bar.vue')['default']
    ProgressCircle: typeof import('./src/components/player/progress-circle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/base/scroll/scroll.vue')['default']
    SearchInput: typeof import('./src/components/search/search-input.vue')['default']
    SearchList: typeof import('./src/components/search/search-list.vue')['default']
    Slider: typeof import('./src/components/base/slider/slider.vue')['default']
    SongList: typeof import('./src/components/base/song-list/song-list.vue')['default']
    Suggest: typeof import('./src/components/search/suggest.vue')['default']
    Tab: typeof import('./src/components/tab/tab.vue')['default']
    WrapScroll: typeof import('./src/components/wrap-scroll/wrap-scroll.vue')['default']
  }
}

export { }
